---
title: "HumAnE_Dogs_General"
author: "Jack Sudds"
date: "2023-01-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Packages}
library(tidyverse) #install.packages("tidyverse")
library(ggplot2)
library(readxl) #install.packages("readxl")
library(here) #install.packages("here")
library(janitor) #install.packages("janitor")
library(kableExtra) #install.packages("kableExtra")
library(skimr) #install.packages("skimr")
library(dplyr) #install.packages("dplyr")
library(RColorBrewer) #install.packages("RColorBrewer")
library(formattable) #install.packages("formattable")
library(wesanderson)#install.packages("wesanderson")
library(reshape2)
library(ggtext) #install.packages("ggtext")
library(psych)#install.packages("psych")
library(BSDA) #install.packages("BSDA")
library(qpcR) #install.packages("qpcR")
library(ggsci)#install.packages("ggsci")
library(gghighlight)#install.packages("gghighlight")
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggrepel) #install.packages("ggrepel")
library(ggspatial)#install.packages("ggspatial")
```

```{r import data}

Dog_Locations <- read_excel("~/Archaeology PhD/Misc/HumAnE/Dog Paper/general.xlsx")

world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)

```

```{r}

ggplot(data = world) +
  geom_sf(fill= "antiquewhite") +
  theme(
    panel.grid.major = element_line(color = gray(.5), linetype = "dashed", size = 0.5),
    panel.background = element_rect(fill = "aliceblue")
    ) +
  labs(
    title = "Slovenia Sites"
  ) +
  coord_sf(xlim = c(13.3, 16.6), ylim = c(45.2, 47), expand = FALSE) +
  xlab("Longitude") + ylab("Latitude") +
  annotation_scale(location = "br", width_hint = 0.5) +
    annotation_north_arrow(location = "br", which_north = "true", 
        pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"),
        style = north_arrow_fancy_orienteering) +
  geom_point(data = Dog_Locations, aes(x = Long, y= Lat)) +
  geom_label_repel(data = Dog_Locations, aes(label = Site, x = Long, y = Lat, fontface = "bold"),label.size = NA, fill = "white", color = "black", segment.colour = "white", max.overlaps  = Inf, min.segment.length = 0) +
  geom_label_repel(data = Dog_Locations, aes(label = No, x = Long, y = Lat, fontface = "bold"),label.size = NA, fill = "white", color = "red", segment.colour = "white", max.overlaps  = Inf, min.segment.length = 10)

```